<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Grid $block */
$customerAddressView = $block->getData('customer_address');
?>

<div class="block block-addresses-list">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Additional Address Entries')) ?></strong></div>
    <div class="block-content">
        <?php if ($_pAddsses = $block->getAdditionalAddresses()) : ?>

            <div class="table-wrapper additional-addresses">
              <?php foreach ($_pAddsses as $address) : ?>
              <div class="box box-address-shipping">
                <span>
                  <div><?= $block->escapeHtml($address->getFirstname()) . " " . $block->escapeHtml($address->getLastname()) ?></div>
                  <div><?= $block->escapeHtml($block->getStreetAddress($address)) ?></div>
                  <div> <?= $block->escapeHtml($block->getCountryByCode($address->getCountryId())) . " - " . $block->escapeHtml($address->getRegion()->getRegion()) . " - " . $block->escapeHtml($address->getCity())?></div>
                  <div class="green"><?= $block->escapeHtml($address->getTelephone()) ?></div>
                </span>
                <div data-th="" class="col actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $address->getId()])) ?>">
                      <span><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span>
                    </a>
                    <a class="action delete" href="#" role="delete-address" data-address="<?= $block->escapeHtmlAttr($address->getId()) ?>">
                      <span><i class="fa fa-trash" aria-hidden="true"></i></span>
                    </a>
                </div>
              </div>
              <?php endforeach; ?>
            </div>
            <?php if ($block->getChildHtml('pager')) : ?>
                <div class="customer-addresses-toolbar toolbar bottom"><?= $block->getChildHtml('pager') ?></div>
            <?php endif ?>
        <?php else : ?>
            <p class="empty"><?= $block->escapeHtml(__('You have no other address entries in your address book.')) ?></p>
        <?php endif ?>
    </div>
</div>

<div class="actions-toolbar">
    <div class="primary">
        <button type="button" role="add-address" title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>" class="action primary add"><span><?= $block->escapeHtml(__('Add New Address')) ?></span></button>
    </div>
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "td a[role='delete-address']",
                "deleteUrlPrefix": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteUrl())) ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
