<?php
/*
* 	Block Guide
*	Magento menu: $block->getChildHtml('store.menu');
*	Language: $block->getChildHtml('store_language');
*	Currency: $block->getChildHtml('currency');
*	Top Links: $block->getChildHtml('top.links');
*	Skip Content Block: $block->getChildHtml('skip_to_content');
*	Logo: $block->getChildHtml('logo');
*	Mini Cart: $block->getChildHtml('minicart');
*	Search: $block->getChildHtml('topSearch');
*	Static block: $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('your_block_identifier')->toHtml();
*/
?>

<?php
	$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');

	$blockEnable = explode(",",$themeSettingConfig->getStoreConfig('themesettings/header/elements'));
	$cartType = $themeSettingConfig->getStoreConfig('themesettings/header/mini_cart_type');
	$accountType = $themeSettingConfig->getStoreConfig('themesettings/header/my_account_type');
	$searchType = $themeSettingConfig->getStoreConfig('themesettings/header/search_type');
	$loginForm = $themeSettingConfig->getStoreConfig('themesettings/header/my_account_form');
	$stickyMenu = $themeSettingConfig->getStoreConfig('themesettings/header/sticky_menu');
	$stickyMenuMobile = $themeSettingConfig->getStoreConfig('themesettings/header/sticky_menu_mobile');
	$_headerVer = $themeSettingConfig->getStoreConfig('themesettings/header/header_version');
	if($_headerVer == ''){ $_headerVer = 'header1'; }

	$addtionClass = "search-" . $searchType;
	if($cartType == 'slide'){
		$addtionClass .= " minicart-slide";
	}
	if($accountType == 'slide'){
		$addtionClass .= " myaccount-slide";
	}
	if(!$stickyMenu){
		$addtionClass .= " active-sticky";
		if(!$stickyMenuMobile){
			$addtionClass .= " active-sticky-mb";
		}
	}
	$settingContentCondition =  false;
	if((in_array('store', $blockEnable) && trim(preg_replace('/\s+/', ' ', $block->getChildHtml('store_language')))) || (in_array('curency', $blockEnable) && trim(preg_replace('/\s+/', ' ', $block->getChildHtml('currency')))) || (in_array('static1', $blockEnable) && trim(preg_replace('/\s+/', ' ', $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_1')->toHtml()))) || (in_array('static2', $blockEnable) && trim(preg_replace('/\s+/', ' ', $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_2')->toHtml())))){
		$settingContentCondition = true;
	}
	if($themeSettingConfig->getStoreConfig('themesettings/footer/footer_bottom_custom_copyright')){
		$copyright = $themeSettingConfig->getStoreConfig('themesettings/footer/footer_bottom_copyright');
	}else {
		$copyright = $block->getChildHtml('copyright');
	}
?>
<div class="header-area <?php if($_headerVer == 'header2' || $_headerVer == 'header4' || $_headerVer == 'header6'   ): ?>right-slide-menu<?php endif ?> <?= $_headerVer ?> <?= $addtionClass ?>">
	<?php /* Header 1 */ ?>
	<?php if($_headerVer == 'header1'): ?>

		<div class="top-header">
			<div class="left-top-header">
				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_5_custom_static_block')->toHtml(); ?>
			</div>
			<div class="right-top-header">
				<div class="setting-site-content">
					<div class="list-block">
						<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_5_track_order')->toHtml(); ?>
						<div class="item customer-web-config curency">
							<?php if(in_array('curency', $blockEnable)): ?>
								<?= $block->getChildHtml('currency'); ?>
							<?php endif ?>

						</div>
						<div class="item customer-web-config language">
							<?php if(in_array('store', $blockEnable)): ?>
								<?= $block->getChildHtml('store_language'); ?>
							<?php endif ?>
						</div>
						<div class="item social">
							<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_5_social')->toHtml(); ?>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="middle-header">
			<div class="megamenu_action mobile"><button class="megamenu_action_mb" type="button"><span class="icon-menu"></span></button></div>
			<?= $block->getChildHtml('logo') ?>


			<?php if(in_array('minicart', $blockEnable) || in_array('wishlist', $blockEnable) || in_array('search', $blockEnable) || in_array('account', $blockEnable) || in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
			<div class="right-content">

					<?php if(in_array('search', $blockEnable)): ?>
						<?= $block->getChildHtml('topSearch') ?>
					<?php endif ?>

					<?php if(in_array('account', $blockEnable)): ?>
						<div class="header-top-links">
							<div class="actions">
								<span class="action top-links theme-header-icon"></span>
							</div>
							<?= $block->getChildHtml('login.form.header'); ?>
						</div>
					<?php endif ?>

					<?php if(in_array('wishlist', $blockEnable)): ?>
						<?= $block->getChildHtml('wishlist-link-header') ?>
					<?php endif ?>

					<?php if(in_array('minicart', $blockEnable)): ?>
						<?= $block->getChildHtml('minicart') ?>
					<?php endif ?>
					<?php if(in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
						<?php if($settingContentCondition): ?>
							<div class="setting-site">
								<div class="actions">
									<button class="action setting" type="button"><span class="icon-setting-web theme-header-icon"></span></button>
								</div>
								<div class="setting-site-content">
									<div class="ct">
										<div class="actions-close">
											<button id="close-setting-site"><span class="icon-cross2"></span></button>
										</div>
										<div class="customer-web-config">
											<?php if(in_array('store', $blockEnable)): ?>
												<?= $block->getChildHtml('store_language'); ?>
											<?php endif ?>
											<?php if(in_array('curency', $blockEnable)): ?>
												<?= $block->getChildHtml('currency'); ?>
											<?php endif ?>
										</div>
										<?php if(in_array('static1', $blockEnable)): ?>
											<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_1')->toHtml(); ?>
										<?php endif ?>
										<?php if(in_array('static2', $blockEnable)): ?>
											<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_2')->toHtml(); ?>
										<?php endif ?>
									</div>
								</div>
							</div>
						<?php endif ?>
					<?php endif ?>
				<div class="megamenu_action tablet"><button class="megamenu_action_mb" type="button"><span class="icon-menu"></span></button></div>
			</div>
			<?php endif ?>
		</div>
		<div class="bottom-header">
			<div class="horizontal-menu<?php if(!$block->getChildHtml('megamenu')): ?> mgt-menu<?php endif ?>">
				<button class="close-menu-site" id="close-menu-site"><span class="icon-cross2"></span></button>
				<?php if($block->getChildHtml('megamenu')): ?>
					<?= $block->getChildHtml('megamenu') ?>
				<?php else: ?>
					<?= $block->getChildHtml('store.menu') ?>
				<?php endif ?>
			</div>
		</div>

	<?php elseif($_headerVer == 'header2'): ?>
	<?php /* Header 2 */ ?>
        <?php if($themeSettingConfig->getStoreConfig('themesettings/header/display_top_header') && in_array('static3', $blockEnable)): ?>
			<div class="top-header">
				<div class="frame">
					<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_custom_static_block_3')->toHtml(); ?>
				</div>
			</div>
        <?php endif ?>
        <div class="frame">
            <div class="middle-header">
                <div class="horizontal-menu<?php if(!$block->getChildHtml('megamenu')): ?> mgt-menu<?php endif ?>">
                    <button class="close-menu-site" id="close-menu-site"><span class="icon-cross2"></span></button>
                    <?php if($block->getChildHtml('megamenu')): ?>
                        <?= $block->getChildHtml('megamenu') ?>
                    <?php else: ?>
                        <?= $block->getChildHtml('store.menu') ?>
                    <?php endif ?>
                </div>
                <?php if(in_array('search', $blockEnable)): ?>
                    <?= $block->getChildHtml('topSearch') ?>
                <?php endif ?>

                <?= $block->getChildHtml('logo') ?>

                <?php if(in_array('minicart', $blockEnable) || in_array('wishlist', $blockEnable) || in_array('search', $blockEnable) || in_array('account', $blockEnable) || in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
                    <div class="right-content">
                        <?php if(in_array('account', $blockEnable)): ?>
                            <div class="header-top-links">
                                <div class="actions">
                                    <span class="action top-links theme-header-icon"></span>
                                </div>
                                <?= $block->getChildHtml('login.form.header'); ?>
                            </div>
                        <?php endif ?>

                        <?php if(in_array('wishlist', $blockEnable)): ?>
                            <?= $block->getChildHtml('wishlist-link-header') ?>
                        <?php endif ?>

                        <?php if(in_array('minicart', $blockEnable)): ?>
                            <?= $block->getChildHtml('minicart') ?>
                        <?php endif ?>
                        <?php if(in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
                            <?php if($settingContentCondition): ?>
                                <div class="setting-site">
                                    <div class="actions">
                                        <button class="action setting" type="button"><span class="icon-setting-web theme-header-icon"></span></button>
                                    </div>
                                    <div class="setting-site-content">
                                        <div class="ct">
                                            <div class="actions-close">
                                                <button id="close-setting-site"><span class="icon-cross2"></span></button>
                                            </div>
                                            <div class="customer-web-config">
                                                <?php if(in_array('store', $blockEnable)): ?>
                                                    <?= $block->getChildHtml('store_language'); ?>
                                                <?php endif ?>
                                                <?php if(in_array('curency', $blockEnable)): ?>
                                                    <?= $block->getChildHtml('currency'); ?>
                                                <?php endif ?>
                                            </div>
                                            <?php if(in_array('static1', $blockEnable)): ?>
                                                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_1')->toHtml(); ?>
                                            <?php endif ?>
                                            <?php if(in_array('static2', $blockEnable)): ?>
                                                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_2')->toHtml(); ?>
                                            <?php endif ?>
                                        </div>
                                    </div>
                                </div>
                            <?php endif ?>
                        <?php endif ?>
                    <div class="megamenu_action deskop"><button class="megamenu_action_mb" type="button"><span class="icon-menu"></span></button></div>
                </div>
                <?php endif ?>
            </div>
		</div>
    <?php /* Header 3 */ ?>
    <?php elseif($_headerVer == 'header3'): ?>
        <?php if($themeSettingConfig->getStoreConfig('themesettings/header/display_top_header') && in_array('static3', $blockEnable)): ?>
            <div class="top-header">
                <div class="frame">
                    <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_custom_static_block_3')->toHtml(); ?>
                </div>
            </div>
        <?php endif ?>
		<div class="frame">
            <div class="middle-header">
                <div class="megamenu_action mobile"><button class="megamenu_action_mb" type="button"><span class="icon-menu"></span></button></div>
                <?= $block->getChildHtml('logo') ?>

                <div class="horizontal-menu<?php if(!$block->getChildHtml('megamenu')): ?> mgt-menu<?php endif ?>">
                    <button class="close-menu-site" id="close-menu-site"><span class="icon-cross2"></span></button>
                    <?php if($block->getChildHtml('megamenu')): ?>
                        <?= $block->getChildHtml('megamenu') ?>
                    <?php else: ?>
                        <?= $block->getChildHtml('store.menu') ?>
                    <?php endif ?>
                </div>

                <?php if(in_array('minicart', $blockEnable) || in_array('wishlist', $blockEnable) || in_array('search', $blockEnable) || in_array('account', $blockEnable) || in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
                <div class="right-content">

                        <?php if(in_array('search', $blockEnable)): ?>
                            <?= $block->getChildHtml('topSearch') ?>
                        <?php endif ?>

                        <?php if(in_array('account', $blockEnable)): ?>
                            <div class="header-top-links">
                                <div class="actions">
                                    <span class="action top-links theme-header-icon"></span>
                                </div>
                                <?= $block->getChildHtml('login.form.header'); ?>
                            </div>
                        <?php endif ?>

                        <?php if(in_array('wishlist', $blockEnable)): ?>
                            <?= $block->getChildHtml('wishlist-link-header') ?>
                        <?php endif ?>

                        <?php if(in_array('minicart', $blockEnable)): ?>
                            <?= $block->getChildHtml('minicart') ?>
                        <?php endif ?>
                        <?php if(in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
                            <?php if($settingContentCondition): ?>
                                <div class="setting-site">
                                    <div class="actions">
                                        <button class="action setting" type="button"><span class="icon-setting-web theme-header-icon"></span></button>
                                    </div>
                                    <div class="setting-site-content">
                                        <div class="ct">
                                            <div class="actions-close">
                                                <button id="close-setting-site"><span class="icon-cross2"></span></button>
                                            </div>
                                            <div class="customer-web-config">
                                                <?php if(in_array('store', $blockEnable)): ?>
                                                    <?= $block->getChildHtml('store_language'); ?>
                                                <?php endif ?>
                                                <?php if(in_array('curency', $blockEnable)): ?>
                                                    <?= $block->getChildHtml('currency'); ?>
                                                <?php endif ?>
                                            </div>
                                            <?php if(in_array('static1', $blockEnable)): ?>
                                                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_1')->toHtml(); ?>
                                            <?php endif ?>
                                            <?php if(in_array('static2', $blockEnable)): ?>
                                                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_2')->toHtml(); ?>
                                            <?php endif ?>
                                        </div>
                                    </div>
                                </div>
                            <?php endif ?>
                        <?php endif ?>
                    <div class="megamenu_action tablet"><button class="megamenu_action_mb" type="button"><span class="icon-menu"></span></button></div>
                </div>
                <?php endif ?>
            </div>
        </div>
    <?php /* Header 4 */ ?>
    <?php elseif($_headerVer == 'header4'): ?>
         <?php if($themeSettingConfig->getStoreConfig('themesettings/header/display_top_header') && in_array('static3', $blockEnable)): ?>
            <div class="top-header">
                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_custom_static_block_3')->toHtml(); ?>
            </div>
        <?php endif ?>
        <div class="middle-header">
            <div class="horizontal-menu<?php if(!$block->getChildHtml('megamenu')): ?> mgt-menu<?php endif ?>">
                <button class="close-menu-site" id="close-menu-site"><span class="icon-cross2"></span></button>
                <?php if($block->getChildHtml('megamenu')): ?>
                    <?= $block->getChildHtml('megamenu') ?>
                <?php else: ?>
                    <?= $block->getChildHtml('store.menu') ?>
                <?php endif ?>
            </div>

            <?= $block->getChildHtml('logo') ?>

            <?php if(in_array('minicart', $blockEnable) || in_array('wishlist', $blockEnable) || in_array('search', $blockEnable) || in_array('account', $blockEnable) || in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
                <div class="right-content">
                    <?php if(in_array('search', $blockEnable)): ?>
                        <?= $block->getChildHtml('topSearch') ?>
                    <?php endif ?>
                    <?php if(in_array('account', $blockEnable)): ?>
                        <div class="header-top-links">
                            <div class="actions">
                                <span class="action top-links theme-header-icon"></span>
                            </div>
                            <?= $block->getChildHtml('login.form.header'); ?>
                        </div>
                    <?php endif ?>

                    <?php if(in_array('wishlist', $blockEnable)): ?>
                        <?= $block->getChildHtml('wishlist-link-header') ?>
                    <?php endif ?>

                    <?php if(in_array('minicart', $blockEnable)): ?>
                        <?= $block->getChildHtml('minicart') ?>
                    <?php endif ?>
                    <?php if(in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
                        <?php if($settingContentCondition): ?>
                            <div class="setting-site">
                                <div class="actions">
                                    <button class="action setting" type="button"><span class="icon-setting-web theme-header-icon"></span></button>
                                </div>
                                <div class="setting-site-content">
                                    <div class="ct">
                                        <div class="actions-close">
                                            <button id="close-setting-site"><span class="icon-cross2"></span></button>
                                        </div>
                                        <div class="customer-web-config">
                                            <?php if(in_array('store', $blockEnable)): ?>
                                                <?= $block->getChildHtml('store_language'); ?>
                                            <?php endif ?>
                                            <?php if(in_array('curency', $blockEnable)): ?>
                                                <?= $block->getChildHtml('currency'); ?>
                                            <?php endif ?>
                                        </div>
                                        <?php if(in_array('static1', $blockEnable)): ?>
                                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_1')->toHtml(); ?>
                                        <?php endif ?>
                                        <?php if(in_array('static2', $blockEnable)): ?>
                                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_2')->toHtml(); ?>
                                        <?php endif ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif ?>
                    <?php endif ?>
                <div class="megamenu_action deskop"><button class="megamenu_action_mb" type="button"><span class="icon-menu"></span></button></div>
            </div>
            <?php endif ?>
        </div>
	<?php /* Header 5 */ ?>
	<?php elseif($_headerVer == 'header5'): ?>
		<div class="top-header">
			<div class="left-top-header">
				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_5_custom_static_block')->toHtml(); ?>
			</div>
			<div class="right-top-header">
				<div class="setting-site-content">
					<div class="list-block">
						<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_5_track_order')->toHtml(); ?>
						<div class="item customer-web-config curency">
							<?php if(in_array('curency', $blockEnable)): ?>
								<?= $block->getChildHtml('currency'); ?>
							<?php endif ?>
						</div>
						<div class="item customer-web-config language">
							<?php if(in_array('store', $blockEnable)): ?>
								<?= $block->getChildHtml('store_language'); ?>
							<?php endif ?>
						</div>
            <div class="item switcher-store" style="display: none">
                <?= $block->getChildHtml('store_switcher'); ?>
            </div>
						<div class="item social">
							<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_5_social')->toHtml(); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="middle-header">
			<div class="megamenu_action mobile"><button class="megamenu_action_mb" type="button"><span class="icon-menu"></span></button></div>
			<?= $block->getChildHtml('logo') ?>



			<?php if(in_array('minicart', $blockEnable) || in_array('wishlist', $blockEnable) || in_array('search', $blockEnable) || in_array('account', $blockEnable) || in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
			<div class="right-content">

					<?php if(in_array('search', $blockEnable)): ?>
						<?= $block->getChildHtml('topSearch') ?>
					<?php endif ?>

					<?php if(in_array('account', $blockEnable)): ?>
						<div class="header-top-links">
							<div class="actions">
								<span class="action top-links theme-header-icon"></span>
							</div>
							<?= $block->getChildHtml('login.form.header'); ?>
						</div>
					<?php endif ?>

					<?php if(in_array('wishlist', $blockEnable)): ?>
						<?= $block->getChildHtml('wishlist-link-header') ?>
					<?php endif ?>

					<?php if(in_array('minicart', $blockEnable)): ?>
						<?= $block->getChildHtml('minicart') ?>
					<?php endif ?>

				<div class="megamenu_action tablet"><button class="megamenu_action_mb" type="button"><span class="icon-menu"></span></button></div>

				<?php if(in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
					<?php if($settingContentCondition): ?>
						<!-- Setting screen for header 5-->
						<div class="setting-site">
							<div class="setting-site-content">
								<div class="ct">
									<!-- Level 1 Categories-->
								<script>
									require(['jquery'],function(){
									    jQuery(document).ready(function() {
													var screenHeight = jQuery(window).height();
													jQuery('ul#menu-content-mobile li:first').addClass('active');
													jQuery('.right-side-menu').height(screenHeight - 177);
													jQuery('.left-side-menu').height(screenHeight - 177);
													var currentCategoryId = jQuery('ul#menu-content-mobile li:first').attr('id');
													var currentUrl = "<?php echo $block->getBaseUrl().'mgsthemesetting/menu/subs' ?>";
													jQuery.ajax({
															url: currentUrl,
															type: "POST",
															data: {categoryId:currentCategoryId},
															showLoader: true,
															cache: false,
															success: function(response){
																	jQuery("#sub-menu-content").html(response);
															}
													});
									        jQuery(".parent_menu_item").click(function(){
									            var url = "<?php echo $block->getBaseUrl().'mgsthemesetting/menu/subs' ?>";
															var CategoryId = jQuery(this).attr('id');
															jQuery('ul#menu-content-mobile li:first').removeClass('active');
									            jQuery.ajax({
									            url: url,
									            type: "POST",
									            data: {categoryId:CategoryId},
									            showLoader: true,
									            cache: false,
									            success: function(response){
									                jQuery("#sub-menu-content").html(response);
									            }
									        });
									        return false;
									        });
									    });
									});
									</script>
									<div class="right-side-menu">
										<ul id="menu-content-mobile">
										<?php
											$itemsBlock = $block->getLayout()->createBlock('MGS\ThemeSettings\Block\Menu\Items');
											$url = $itemsBlock->getMediaUrl();
											$categories = $itemsBlock->getCategories();
											foreach ($categories as $category){ ?>
												<li id="<?php echo $category->getId(); ?>" class="parent_menu_item">
													<a href="javascript:void(0)">
														<?php
														if (!empty($category->getThumbnail())) {
								                $icon = trim($url, '/') . '/catalog/category/' . $category->getThumbnail();
								            } else {
										          $icon = trim($url, '/') . '/catalog/product/' . "placeholder/default/alsaif-placeholder.png";
										        }
														?>
														<img src="<?php echo $icon; ?>">
														<span><?php echo $category->getName(); ?></span>
													</a>
												</li>
											<?php } ?>
											</ul>
									</div>
  								<div class="left-side-menu">
										<div class="menu-wrapper" id="sub-menu-content">

										</div>
									</div>
								</div>
							</div>
						</div>
					<?php endif ?>
				<?php endif ?>
			</div>
			<?php endif ?>
		</div>
		<div class="bottom-header">
			<div class="horizontal-menu<?php if(!$block->getChildHtml('megamenu')): ?> mgt-menu<?php endif ?>">
				<button class="close-menu-site" id="close-menu-site"><span class="icon-cross2"></span></button>
				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_custom_static_block_menu_1')->toHtml(); ?>
				<?php if($block->getChildHtml('megamenu')): ?>
					<?= $block->getChildHtml('megamenu') ?>
				<?php else: ?>
					<?= $block->getChildHtml('store.menu') ?>
				<?php endif ?>
				<div class="top-mobile-menu-action">
					<ul>
						<li>
							<div class="div-inline">
								<span><img src="<?php echo trim($url, '/') . '/wysiwyg/earth-globe-svgrepo-com_3x.png'; ?>" class="menu-icon"><?php echo __("Language"); ?></span>
							</div>
							<?= $block->getChildHtml('store_language'); ?>
						</li>
						<li>
							<?php if(in_array('curency', $blockEnable)): ?>
								<div class="div-inline">
									<span><img src="<?php echo trim($url, '/') . '/wysiwyg/earth-globe-svgrepo-com_3x.png'; ?>" class="menu-icon"><?php echo __("Currency"); ?></span>
								</div>
								<?= $block->getChildHtml('currency'); ?>
							<?php endif ?>
						</li>
						<li  style="display: none">
							<div class="div-inline">
								<span><img src="<?php echo trim($url, '/') . '/wysiwyg/earth-globe-svgrepo-com_3x.png'; ?>" class="menu-icon"><?php echo __("Country"); ?></span>
							</div>
							<?= $block->getChildHtml('store_switcher'); ?>
						</li>
					</ul>
				</div>
				<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_custom_static_block_menu_2')->toHtml(); ?>
			</div>
		</div>

	<?php /* Header 6 */ ?>
    <?php elseif($_headerVer == 'header6'): ?>
         <?php if($themeSettingConfig->getStoreConfig('themesettings/header/display_top_header') && in_array('static3', $blockEnable)): ?>
            <div class="top-header">
                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_custom_static_block_3')->toHtml(); ?>
            </div>
        <?php endif ?>
        <div class="middle-header">
            <div class="horizontal-menu<?php if(!$block->getChildHtml('megamenu')): ?> mgt-menu<?php endif ?>">
                <button class="close-menu-site" id="close-menu-site"><span class="icon-cross2"></span></button>
                <?php if($block->getChildHtml('megamenu')): ?>
                    <?= $block->getChildHtml('megamenu') ?>
                <?php else: ?>
                    <?= $block->getChildHtml('store.menu') ?>
                <?php endif ?>
            </div>

            <div class="left-content">
                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_4')->toHtml(); ?>

                <?php if(in_array('search', $blockEnable)): ?>
                    <?= $block->getChildHtml('topSearch') ?>
                <?php endif ?>
            </div>

            <?= $block->getChildHtml('logo') ?>

            <?php if(in_array('minicart', $blockEnable) || in_array('wishlist', $blockEnable) || in_array('search', $blockEnable) || in_array('account', $blockEnable) || in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
                <div class="right-content">
                    <?php if(in_array('account', $blockEnable)): ?>
                        <div class="header-top-links">
                            <div class="actions">
                                <span class="action top-links theme-header-icon"></span>
                            </div>
                            <?= $block->getChildHtml('login.form.header'); ?>
                        </div>
                    <?php endif ?>

                    <?php if(in_array('wishlist', $blockEnable)): ?>
                        <?= $block->getChildHtml('wishlist-link-header') ?>
                    <?php endif ?>

                    <?php if(in_array('minicart', $blockEnable)): ?>
                        <?= $block->getChildHtml('minicart') ?>
                    <?php endif ?>
                    <?php if(in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
                        <?php if($settingContentCondition): ?>
                            <div class="setting-site">
                                <div class="actions">
                                    <button class="action setting" type="button"><span class="icon-setting-web theme-header-icon"></span></button>
                                </div>
                                <div class="setting-site-content">
                                    <div class="ct">
                                        <div class="actions-close">
                                            <button id="close-setting-site"><span class="icon-cross2"></span></button>
                                        </div>
                                        <div class="customer-web-config">
                                            <?php if(in_array('store', $blockEnable)): ?>
                                                <?= $block->getChildHtml('store_language'); ?>
                                            <?php endif ?>
                                            <?php if(in_array('curency', $blockEnable)): ?>
                                                <?= $block->getChildHtml('currency'); ?>
                                            <?php endif ?>
                                        </div>
                                        <?php if(in_array('static1', $blockEnable)): ?>
                                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_1')->toHtml(); ?>
                                        <?php endif ?>
                                        <?php if(in_array('static2', $blockEnable)): ?>
                                            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_2')->toHtml(); ?>
                                        <?php endif ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif ?>
                    <?php endif ?>
                    <div class="megamenu_action deskop"><button class="megamenu_action_mb" type="button"><span><?= __('Menu');?></span><i class="icon-menu"></i></button></div>
            </div>
            <?php endif ?>
        </div>

	<?php /*Header 7 left sidebar*/?>
	<?php elseif($_headerVer == 'header7'): ?>
		<div class="top-header">
			<?= $block->getChildHtml('logo') ?>
			<?php if(in_array('minicart', $blockEnable) || in_array('wishlist', $blockEnable) || in_array('search', $blockEnable) || in_array('account', $blockEnable) || in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
				<div class="header-links">
					<?php if(in_array('account', $blockEnable)): ?>
						<div class="header-top-links">
							<div class="account actions">
								<span class="action top-links theme-header-icon"></span>
							</div>
							<?= $block->getChildHtml('login.form.header'); ?>
						</div>
					<?php endif ?>

					<?php if(in_array('wishlist', $blockEnable)): ?>
						<?= $block->getChildHtml('wishlist-link-header') ?>
					<?php endif ?>

					<?php if(in_array('minicart', $blockEnable)): ?>
						<?= $block->getChildHtml('minicart') ?>
					<?php endif ?>
					<?php if(in_array('store', $blockEnable) || in_array('curency', $blockEnable) || in_array('static1', $blockEnable) || in_array('static2', $blockEnable)): ?>
					<?php if($settingContentCondition): ?>
					<div class="setting-site">
						<div class="actions">
							<button class="action setting" type="button"><span class="icon-setting-web theme-header-icon"></span></button>
						</div>
						<div class="setting-site-content">
							<div class="ct">
								<div class="actions-close">
									<button id="close-setting-site"><span class="icon-cross2"></span></button>
								</div>
								<div class="customer-web-config">
									<?php if(in_array('store', $blockEnable)): ?>
										<?= $block->getChildHtml('store_language'); ?>
									<?php endif ?>
									<?php if(in_array('curency', $blockEnable)): ?>
										<?= $block->getChildHtml('currency'); ?>
									<?php endif ?>
								</div>
								<?php if(in_array('static1', $blockEnable)): ?>
									<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_custom_static_block_1')->toHtml(); ?>
								<?php endif ?>
							</div>
						</div>
					</div>
					<?php endif ?>
					<div class="megamenu_action tablet  mobile"><button class="megamenu_action_mb" type="button"><span class="icon-menu"></span></button></div>
				</div>
			<?php endif ?>
		</div>
		<div class="middle-header">
			<button class="close-menu-site mobile" id="close-menu-site"><span class="icon-cross2"></span></button>
			<?php if(in_array('search', $blockEnable)): ?>
				<?= $block->getChildHtml('topSearch') ?>
			<?php endif ?>
			<div class="horizontal-menu<?php if(!$block->getChildHtml('megamenu')): ?> mgt-menu<?php endif ?>">
				<?php if($block->getChildHtml('megamenu')): ?>
					<?= $block->getChildHtml('megamenu') ?>
				<?php else: ?>
					<?= $block->getChildHtml('store.menu') ?>
				<?php endif ?>

			</div>

            <?php endif ?>
			<div class="bt-content ">
				<div><?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_header_5_social')->toHtml(); ?></div>
				<div><address><?= $copyright ?></address></div>
			</div>
		</div>

	</div>

	<?php endif ?>
	<?php // Search Auto Complete ?>
	<?php if($searchType != "icon-popup"): ?>
		<?= $block->getChildHtml('mgs.instant.search.autocomplete.default') ?>
	<?php endif ?>
</div>

<?php /* Bottom Tabs Mobile */ ?>
<div id="js_mobile_tabs" class="header-mobile-tabs--bottom">
	<ul>
		<li>
			<a href="<?php echo $block->getBaseUrl()?>">
				<button class="action-mb-tabs" id="back-home-action" type="button">
					<span class="icon-building"></span>
					<span class="tabbar-label"><?php echo __("Home"); ?></span>
				</button>
			</a>
		</li>
		<li>
			<button id="categories-web-action" type="button">
				<span class="icon-categories-web"></span>
				<span class="tabbar-label"><?php echo __("Categories"); ?></span>
			</button>
		</li>
		<li>
			<a href="<?php echo $block->getBaseUrl().'alsaif-gallery-offers' ?>">
				<button id="deals-web-action" type="button">
					<span class="icon-deals-web"></span>
					<span class="tabbar-label"><?php echo __("Deals"); ?></span>
				</button>
			</a>
		</li>
		<li>
			<button class="action-mb-tabs" id="my-account-action" type="button">
				<span class="icon-my-account"></span>
				<span class="tabbar-label"><?php echo __("Account"); ?></span>
			</button>
		</li>
		<li>
			<button class="action-mb-tabs" data-bind="scope: 'minicart_content'" id="cart-top-action" type="button">
				<span class="icon-cart-top"></span>
				<span class="counter qty empty"
					  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
					<span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
				</span>
				<span class="tabbar-label"><?php echo __("Cart"); ?></span>
			</button>
		</li>
	</ul>
</div>
