<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_StorePickupWithLocator
 */
?>
<?php
/** @var $block \Amasty\StorePickupWithLocator\Block\Adminhtml\Sales\Order\Create\Shipping\Form */
?>
<section class="admin__page-section -ampickup">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Store Pickup With Locator')) ?></span>
    </div>
    <?php foreach ($block->getFormElements() as $element): ?>
        <?= $element->toHtml(); ?>
    <?php endforeach; ?>
</section>