<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<br />
<table class="shipment-track">
    <thead>
        <tr>
            <th><?= /* @escapeNotVerified */  __('Shipped By') ?></th>
            <th><?= /* @escapeNotVerified */  __('Tracking Number') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($_shipment->getAllTracks() as $_item): ?>
        <?php $trackingNumber = $block->escapeHtml($_item->getNumber()); ?>
        <tr>
            <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
            <?php if ($_item->getCarrierCode() == 'aramex') { ?>
                <td><a href="http://www.aramex.com/track/results?ShipmentNumber=<?php echo $trackingNumber; ?>"><?php echo $trackingNumber; ?></a></td>
            <?php } else { ?>
                <td><a href="https://my-ksa.safe-arrival.com/track?id=<?php echo $trackingNumber; ?>"><?php echo $trackingNumber; ?></a></td>
            <?php } ?>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif; ?>
